import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto my-40">
        <div className="flex gap-10">
          <div className="flex-none w-64">
            <div className="flex flex-col">
              <div className="flex-initial">
                <div className="card shadow-xl image-full bef">
                  <figure>
                    <img src="/assets/suggestions/desktop/background-header.png" />
                  </figure>
                  <div className="justify-end card-body">
                    <h2 className="card-title font-bold">Frontend Mentor</h2>
                    <p className="opacity-75">Feedback Board.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="flex-1 w-64 ...">
            02
          </div>
          <div className="flex-1 w-32 ...">
            03
          </div>
        </div>
      </div>

    </>
  )
}

export default Home
